### PR TITLE
Fix for bug 517387

### PR DESCRIPTION
**Pull request by wajnberg**
Signed-off-by: Moshe Wajnberg <wajnberg@il.ibm.com>

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=517387

**Comment by wajnberg** [comment]
Hello @libingw 

Could you please review these changes ?

This is quite straightforward as this is only call to existent bidiUtils functions to enforce BTD and STT

**Review by libingw — COMMENTED** [review]
Please resolve the conflicts

**Comment by wajnberg** [comment]
Hello @libingw ,

I have rebased my branch.

Could you please review ?

Thank you

**Comment by libingw** [comment]
The code looks good. I will need to test it on your branch from orion.eclipse.org selfhosting. the site is down now will do it later. Thanks.

**Pull request merged**
