### PR TITLE
Bug 521889 - Contribute themes that alter the UX

### PR DESCRIPTION
**Pull request by caseyflynn-google**
Add settings to toggle visibility of items in Orion IDE.

Signed-off-by: Casey Flynn <caseyflynn@google.com>

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=521889

**Comment by snorthov** [comment]
It still seems a bit strange to me that you can hide and show the run bar from inside a theme.  A theme for me is colors and fonts.  What would it mean to show the run bar in a context that is not really set up to configure it?

My vision was that this would be a flag that you set in orion.conf to get a certain "editor only" feel versus an IDE.  You would never want to change this dynamically nor should you be able to do it.

SSQ, thoughts?

**Comment by dimitrovs** [comment]
Just to chime in, I second @snorthov's opinion. At Cloudeity we also use Orion purely as editor and we disabled the run bar and other features in our own fork. In the future it would be nice to allow users to set / import themes in the editor. If we rely on a theme to hide the run bar then themes will not be compatible across deployments that use or don't use the run bar. The theme should be about styling, not configuration.

**Comment by squarti** [comment]
I agree we should not hide portions of the UI using the theming engine.  We should either uses default preferences (i.e. defaults.pref) for client side only changes or orion.conf if there are changes in the server side as well.

**Comment by caseyflynn-google** [comment]
That's fair. This was my approach to handling unwanted UI elements as alternatives would have introduced a much larger scope (e.g. Possibly examining the entire UI to introduce more modularity). If we don't want to go this route (or some alternative of introducing css to hide elements) I can discard this PR and welcome alternate suggestions.

**Pull request closed without merging**
