### PR TITLE
Bug 518549 - BIDI Islamic national calendar is not supported in date stamps

### PR DESCRIPTION
**Pull request by ragabo**
Adding Islamic national calendar as per discussion with **"Steve Northover"** under [this bug](https://bugs.eclipse.org/bugs/show_bug.cgi?id=518549)

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=518549

**Comment by ragabo** [comment]
I have signed the ECA, please take a look into this pull request.

**Comment by ragabo** [comment]
Signed-off-by: Mohamed Ragab <mhdragab@eg.ibm.com>

**Review by soulbeing — APPROVED** [review]
doesn't break anything

**Review by libingw — APPROVED** [review]

**Pull request merged**
