### PR TITLE
Bug 521992 - Create an Accessibility Settings page #654

### PR DESCRIPTION
**Pull request by carmacleod**

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=521992

**Comment by squarti** [comment]
Looks good.  

Should the MD sections be focusable to allow the users to tab into them (for the screen readers)?

**Comment by squarti** [comment]
We could make the "Editor Theme" settings be a link (i.e "#,category=themeSettings").

**Comment by squarti** [comment]
I think we are leaking those new tooltips.

**Comment by carmacleod** [comment]
> Should the MD sections be focusable to allow the users to tab into them (for the screen readers)?

No. Screen reader users prefer to use reading mode for text content.

> We could make the "Editor Theme" settings be a link (i.e "#,category=themeSettings").

Good idea - and IDE Theme, too.

> I think we are leaking those new tooltips.

Thanks - fixed.

**Review by squarti — APPROVED** [review]

**Pull request merged**
